spring:
  application:
    name: friend-service

  datasource:
    url: jdbc:mysql://localhost:3306/unicall_friend_service?createDatabaseIfNotExist=true
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/unicall}
api:
  prefix: /api/v1
server:
  servlet:
    context-path: /friend-service
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

