spring:
  config:
    import: optional:file:../.env[.properties]
  application:
    name: task-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin123}
  data:
    mongodb:
      uri: ${TASK_MONGODB_URI:mongodb://localhost:27017/unicall_task_service}
      auto-index-creation: true

server:
  port: ${TASK_SERVICE_PORT:8090}

api:
  prefix: /api/v1

app:
  notification:
    exchange: ${NOTIFICATION_EXCHANGE:unicall.notification.exchange}
    routing-key-prefix: ${NOTIFICATION_ROUTING_KEY_PREFIX:notification.task}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
