package iuh.fit.chat_service.enums;

public enum ChatAssistantIntent {
    AI_CAPABILITIES,
    SMALL_TALK,
    GENERAL_QA,
    LIST_CONVERSATIONS,
    LIST_MESSAGES,
    SEARCH_KEYWORD,
    SEARCH_SEMANTIC,
    SEARCH_MY_CHAT_SPACE,
    FIND_WHO_SAID,
    TASK_LIST_GROUPS,
    TASK_FIND_BY_NAME,
    TASK_LIST_GROUP_ITEMS,
    TASK_CREATE,
    TASK_UPDATE,
    TASK_DELETE,
    TASK_DETAIL,
    TASK_COMMENT_CREATE,
    TASK_COMMENT_LIST,
    TASK_LIST_MY_ITEMS,
    TASK_LIST_OVERDUE,
    TASK_LIST_DUE_SOON,
    SUMMARIZE_CONVERSATION,
    UNKNOWN
}
