spring:
  application:
    name: identity-service

server:
  servlet:
    context-path: /identity-service
  port: 8082

app:
  prefix: ${API_PREFIX:/api/v1}
  security:
    cookie:
      secure: ${COOKIE_SECURE:false}
      same-site: ${COOKIE_SAME_SITE:Strict}
    keycloak:
      server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
      realm: ${KEYCLOAK_REALM:unicall}
      client-id: ${KEYCLOAK_CLIENT_ID:unicall-client}
      client-secret: ${KEYCLOAK_CLIENT_SECRET:BnaPyiYRiG0LP8sGdQNuCp1eZ32IFIya}
      admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:unicall-admin-client}
      admin-client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:qEtqS9STfjKuzU99109MTtlZfCcL8UBi}

grpc:
  client:
    saga-orchestrator-service:
      address: ${SAGA_ORCHESTRATOR_GRPC_ADDRESS:static://localhost:9096}
      negotiationType: plaintext
  saga-orchestrator:
    deadline-ms: ${SAGA_ORCHESTRATOR_GRPC_DEADLINE_MS:5000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
